### ISSUE TITLE
UnsupportedOperation error

### ISSUE THREAD

**Issue by jimbolaya** [pascalw/remarkable-wifi-conf#1]
I'm trying to run your program on Debian Bullseye. 
Pip seems happy everything is installe:

pip3 install -r ./requirements.txt 
Requirement already satisfied: pyqt5==5.15.2 in /usr/lib/python3/dist-packages (from -r ./requirements.txt (line 1)) (5.15.2)
Requirement already satisfied: pyqt5-sip==12.8.1 in /usr/lib/python3/dist-packages (from -r ./requirements.txt (line 7)) (12.8.1)

But when I run it, I get the following:

echo '' | python3 ./remarkable_wifi_conf.py
Traceback (most recent call last):
  File "/home/user/src/remarkable-wifi-conf/./remarkable_wifi_conf.py", line 53, in <module>
    main()
  File "/home/user/src/remarkable-wifi-conf/./remarkable_wifi_conf.py", line 38, in main
    tty = open('/dev/tty', 'r+')
io.UnsupportedOperation: File or stream is not seekable.

Can you help?

**Comment by pascalw** [comment]
Hi @jimbolaya thanks for the report. I haven't tried on Linux yet, I'll debug it tomorrow and report back here.

**Comment by pascalw** [comment]
Hi @jimbolaya I looked into it already and fixed it. Can you update to the latest commit and try again?

**Comment by pascalw** [comment]
Closing this assuming it's fixed. @jimbolaya please report if it still doesn't work for you.
